[programs.localnet]
video = "8q3BujDbixVgFiytmTLUpHmXWDPTVapKgAx3Jwx54q7K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kirat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
